service: rest-api

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 10
  stage: dev
  region: us-east-1

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: planetas
          method: post
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: planetas/{id}
          method: get
          cors: true
  getAll:
    handler: handler.getAll
    events:
     - http:
         path: planetas
         method: get
         cors: true
  update:
    handler: handler.update
    events:
     - http:
         path: planetas/{id}
         method: put
         cors: true
  delete:
    handler: handler.delete
    events:
     - http:
         path: planetas/{id}
         method: delete
         cors: true

plugins:
- serverless-offline